name: Super-Linter
'on':
  pull_request:
    branches:
      - master
      - main
jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_GITHUB_ACTIONS: false
          VALIDATE_SHELL_SHFMT: false
          VALIDATE_BASH_EXEC: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
